-- Quick setup (copy from here to end)
CREATE TABLE markets (id TEXT PRIMARY KEY, question TEXT NOT NULL, category TEXT, yes_price DECIMAL(10,6), no_price DECIMAL(10,6), volume_24h DECIMAL(15,2), resolution_date TIMESTAMP, resolved BOOLEAN DEFAULT FALSE, liquidity_score DECIMAL(5,3), created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE historical_markets (id TEXT PRIMARY KEY, question TEXT NOT NULL, category TEXT, yes_price DECIMAL(10,6), no_price DECIMAL(10,6), volume_24h DECIMAL(15,2), resolution_date TIMESTAMP NOT NULL, resolution_value DECIMAL(3,2) NOT NULL, resolved_at TIMESTAMP NOT NULL, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE news_events (id SERIAL PRIMARY KEY, timestamp TIMESTAMP NOT NULL DEFAULT NOW(), headline TEXT NOT NULL, keywords TEXT[], source TEXT, sentiment_score DECIMAL(3,2) DEFAULT 0.0, url TEXT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE trader_performance (trader_id TEXT PRIMARY KEY, username TEXT, win_rate DECIMAL(5,2), total_trades INTEGER DEFAULT 0, total_volume DECIMAL(15,2), avg_position_size DECIMAL(15,2), sharpe_ratio DECIMAL(5,2), last_active TIMESTAMP, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE theses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), agent_id TEXT NOT NULL, market_id TEXT NOT NULL, thesis_text TEXT NOT NULL, fair_value DECIMAL(10,6) NOT NULL, current_odds DECIMAL(10,6) NOT NULL, edge DECIMAL(10,6) NOT NULL, conviction DECIMAL(3,2) NOT NULL, horizon TEXT, proposed_action JSONB NOT NULL, status TEXT DEFAULT 'active', created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE portfolio (id INTEGER PRIMARY KEY DEFAULT 1, cash DECIMAL(15,2) NOT NULL DEFAULT 1000.00, total_value DECIMAL(15,2) NOT NULL DEFAULT 1000.00, deployed_pct DECIMAL(5,2) DEFAULT 0.00, daily_pnl DECIMAL(15,2) DEFAULT 0.00, all_time_pnl DECIMAL(15,2) DEFAULT 0.00, updated_at TIMESTAMP DEFAULT NOW(), CONSTRAINT single_portfolio CHECK (id = 1));
INSERT INTO portfolio VALUES (1, 1000.00, 1000.00, 0.00, 0.00, 0.00, NOW()) ON CONFLICT DO NOTHING;
CREATE TABLE positions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), market_id TEXT NOT NULL, thesis_id UUID, side TEXT NOT NULL, shares DECIMAL(15,6) NOT NULL, entry_price DECIMAL(10,6) NOT NULL, current_price DECIMAL(10,6) NOT NULL, pnl DECIMAL(15,2) DEFAULT 0.00, status TEXT DEFAULT 'open', opened_at TIMESTAMP DEFAULT NOW(), closed_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE ic_memos (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), date DATE NOT NULL UNIQUE, memo_text TEXT NOT NULL, portfolio_summary JSONB, trades_count INTEGER DEFAULT 0, win_rate DECIMAL(5,2), daily_return DECIMAL(10,4), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE event_log (id BIGSERIAL PRIMARY KEY, timestamp TIMESTAMP NOT NULL DEFAULT NOW(), event_type TEXT NOT NULL, agent_id TEXT, market_id TEXT, thesis_id UUID, position_id UUID, details JSONB, severity TEXT DEFAULT 'info', created_at TIMESTAMP DEFAULT NOW());
