"""
BASED MONEY - Thesis Model
Represents an agent-generated trade idea/thesis
"""

from dataclasses import dataclass, field
from typing import Dict, Optional, Any
from datetime import datetime
from uuid import UUID, uuid4


@dataclass
class Thesis:
    """
    Represents a trading thesis generated by an agent.

    A thesis is a trade idea with calculated edge, conviction level,
    and proposed action. Each thesis is evaluated by the risk engine
    before execution.
    """

    # Unique identifier
    id: UUID = field(default_factory=uuid4)

    # Agent that generated this thesis
    agent_id: str = ""

    # Market this thesis applies to
    market_id: str = ""

    # Market question (for display purposes)
    market_question: str = ""

    # Human-readable explanation of the thesis
    thesis_text: str = ""

    # Calculated fair value (0.0 to 1.0)
    fair_value: float = 0.0

    # Current market odds (0.0 to 1.0)
    current_odds: float = 0.0

    # Edge: fair_value - current_odds
    edge: float = 0.0

    # Conviction level (0.0 to 1.0, where 1.0 = maximum confidence)
    conviction: float = 0.0

    # Time horizon: 'short' (<7 days), 'medium' (7-30 days), 'long' (>30 days)
    horizon: str = "medium"

    # Proposed trading action: {"side": "YES"|"NO", "size_pct": 0.0-1.0}
    proposed_action: Dict[str, Any] = field(default_factory=dict)

    # Status tracking
    status: str = "active"  # 'active', 'executed', 'expired', 'rejected'

    # Timestamps
    created_at: Optional[datetime] = field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = field(default_factory=datetime.utcnow)

    def __post_init__(self):
        """Validate thesis fields after initialization"""
        # Ensure proposed_action has required keys
        if self.proposed_action and not isinstance(self.proposed_action, dict):
            raise ValueError("proposed_action must be a dictionary")

        if self.proposed_action:
            if "side" not in self.proposed_action:
                self.proposed_action["side"] = "YES"
            if "size_pct" not in self.proposed_action:
                self.proposed_action["size_pct"] = 0.0
        else:
            self.proposed_action = {"side": "YES", "size_pct": 0.0}

        # Validate numeric bounds
        if not 0.0 <= self.fair_value <= 1.0:
            raise ValueError(
                f"fair_value must be between 0.0 and 1.0, got {self.fair_value}"
            )

        if not 0.0 <= self.current_odds <= 1.0:
            raise ValueError(
                f"current_odds must be between 0.0 and 1.0, got {self.current_odds}"
            )

        if not 0.0 <= self.conviction <= 1.0:
            raise ValueError(
                f"conviction must be between 0.0 and 1.0, got {self.conviction}"
            )

        # Validate horizon
        if self.horizon not in ["short", "medium", "long"]:
            raise ValueError(
                f"horizon must be 'short', 'medium', or 'long', got {self.horizon}"
            )

        # Validate side
        if self.proposed_action["side"] not in ["YES", "NO"]:
            raise ValueError(
                f"proposed_action.side must be 'YES' or 'NO', got {self.proposed_action['side']}"
            )

    def to_dict(self) -> dict:
        """Convert thesis to dictionary for database storage"""
        return {
            "id": str(self.id),
            "agent_id": self.agent_id,
            "market_id": self.market_id,
            "market_question": self.market_question,
            "thesis_text": self.thesis_text,
            "fair_value": float(self.fair_value),
            "current_odds": float(self.current_odds),
            "edge": float(self.edge),
            "conviction": float(self.conviction),
            "horizon": self.horizon,
            "proposed_action": self.proposed_action,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Thesis":
        """Create Thesis instance from dictionary"""
        # Convert string UUID back to UUID object
        if "id" in data and isinstance(data["id"], str):
            data["id"] = UUID(data["id"])

        # Convert ISO timestamp strings back to datetime
        if "created_at" in data and isinstance(data["created_at"], str):
            data["created_at"] = datetime.fromisoformat(data["created_at"])
        if "updated_at" in data and isinstance(data["updated_at"], str):
            data["updated_at"] = datetime.fromisoformat(data["updated_at"])

        return cls(**data)

    def is_actionable(self, min_conviction: float = 0.70) -> bool:
        """Check if thesis meets minimum conviction threshold"""
        return self.conviction >= min_conviction and self.status == "active"

    def __repr__(self) -> str:
        """Human-readable representation"""
        return (
            f"Thesis(id={str(self.id)[:8]}..., agent={self.agent_id}, "
            f"market={self.market_id[:20]}..., edge={self.edge:.2%}, "
            f"conviction={self.conviction:.0%}, status={self.status})"
        )
